CREATE TABLE [dbo].[Oblast] (
    [ID]  INT           NOT NULL,
    [Ime] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_Oblast] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UK_Oblast_Ime] UNIQUE NONCLUSTERED ([Ime] ASC)
);

